services:
  - type: web
    name: MammaMia-Private  # Cambia il nome per evitare filtri automatici
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 run.py
    plan: free 
    region: frankfurt  # Ottimo per la latenza italiana
    envVars:
      - key: PORT
        value: 8080
      - key: TMDB_KEY
        sync: false  # Ti verrà chiesto nella Dashboard di Render
      - key: PROXY
        sync: false  # Formato: ["http://user:pass@p.webshare.io:80"]
      - key: PYTHON_VERSION
        value: 3.10.0  # Assicura la compatibilità con FastAPI
      - key: FORWARDPROXY
        sync: false  # Opzionale: utile se usi un forward proxy per Cloudflare
